<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Admin.aspx.cs" Inherits="PizzariaWebsite.Admin" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
  <link rel="stylesheet" href="Style.css"/>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous"/>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <title>Pizzaria</title>
</head>
<body>
    <form id="form1" runat="server"> 
      <div class="navbar">
            <img src="assets/logo.png"  class="logo"/>
            <ul>
                <li><a href="Default.aspx">Home</a></li>
            </ul>
        </div>
        <div class="col-md-12 col-md-pull-2">
            <asp:GridView ID="grid" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="false" UseAccessibleHeader="true" Width="1200px">
                <Columns>
                    <asp:BoundField DataField="OrderID" HeaderText="ID" />
                    <asp:BoundField DataField="Username" HeaderText="Username" />
                    <asp:BoundField DataField="PizzaID" HeaderText="Pizza ID" />
                    <asp:BoundField DataField="Quantity" HeaderText="Quantity" />
                    <asp:BoundField DataField="OrderDateTime" HeaderText="OrderTime" />
                    <asp:BoundField DataField="DeliveryTime" HeaderText="DeliveryTime" />
                    <asp:TemplateField>
                            <ItemTemplate>
                                <asp:TextBox ID="TextBox1" runat="server" Text="" placeholder="Change Delivery time"></asp:TextBox>
                                <asp:Button ID="UpdateBtn" CssClass="delBtn" runat="server" Text="Update" OnClick="UpdateBtn_Click"/>
                            </ItemTemplate>
                        </asp:TemplateField>
                </Columns>
            </asp:GridView>
        </div>
  </form>
</body>
</html>
