<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Cart.aspx.cs" Inherits="PizzariaWebsite.Cart" %>

<!DOCTYPE html>


<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="Style.css"/>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous"/>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <title>Pizzaria</title>
</head>
<body>
  <form id="form1" runat="server"> 
      <div>
          <fieldset class="TopHeader">
              <h1>Pizzaria</h1>
          </fieldset>
      </div>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="Default.aspx"><b>Home</b></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="Menu.aspx"><b>Menu</b></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="MyPage.aspx"><b>My Page</b></a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="Cart.aspx"><b>Cart</b></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="Login.aspx"><b>Login</b></a>  
              </li>
                <li class="nav-item">
                <a class="nav-link" href="Contact.Aspx"><b>Contact</b></a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <section>
        <div class="col-md-12 col-md-pull-2">
            <asp:GridView ID="grid" runat="server" AutoGenerateColumns="false" OnRowDeleting="grid_RowDeleting" AutoGenerateDeleteButton="true" OnSelectedIndexChanged="grid_SelectedIndexChanged" UseAccessibleHeader="true" Width="1173px">
                <Columns>
                    <asp:BoundField DataField="Name" HeaderText="Name" />
                    <asp:BoundField DataField="Price" HeaderText="Price" />
                </Columns>
            </asp:GridView>
        </div>
        <asp:Button runat="server" ID="chkBtn" Text="Checkout" class="btn btn-info btn-md" OnClick="chkBtn_Click"/>
      </section>
  </form>
</body>
</html>